server:
  port: 8080
  servlet:
    context-path: /cyberkit

spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/cyberkit"
        username: admin
        password: supersecretpassword
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    jwt:
      key: rJeZbuqi8K8aGeoHrDOIANmdZUJvMR6lPByuoBNGCs+Q5YuycLMUA0U4JV8DNEpS0KbHrCKbXqn7BzAsRF8Iew==
      # 1 hour = 60 * 60 = 3600
      access-expiration-in-seconds: 3600
      # 100 hour = 60 * 60 * 100 = 360000
      refresh-expiration-in-seconds: 360000
    security:
      oauth2:
        client:
          registration:
            github:
              client-id: Ov23liTmyj7xZJ8xwp8h
              client-secret: a640ec42f683b6a8174925881d39bf1bb896cc8f
              redirect-uri: http://localhost:5173/oauth2/github/callback
              scope: user:email
    payment:
      vnpay:
        vnp_TmnCode: K4G45J9C
        vnp_HashSecret: KJBSE7YUXYVXJSFCL866545N98RE4SEJ
        vnp_PayUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
        vnp_ApiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
        vnp_ReturnUrl: http://localhost:5173/payment/vnpay/callback


