server:
  port: 8080
  servlet:
    context-path: /cyberkit

spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/cyberkit"
        username: admin
        password: supersecretpassword
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    jwt:
      key: rJeZbuqi8K8aGeoHrDOIANmdZUJvMR6lPByuoBNGCs+Q5YuycLMUA0U4JV8DNEpS0KbHrCKbXqn7BzAsRF8Iew==
      # 1 hour = 60 * 60 = 3600
      access-expiration-in-seconds: 3600
      # 100 hour = 60 * 60 * 100 = 360000
      refresh-expiration-in-seconds: 360000